from django.conf.urls.defaults import *
try:
    from mtrack.decorators import login_required
except ImportError:
    from django.contrib.auth.decorators import login_required
from generic.views import *
from .utils import *
from .views import view_submissions, mcd_dashboard, mcdtrac_xforms, submissions_as_csv
from django.views.generic.simple import direct_to_template
from .reports import FHDMaterializedReport

urlpatterns = patterns('',
    url(r'^mcdtrac/demo$', login_required(mcd_dashboard), name='mcds'),
    url(r'^mcdtrac/dhts/$', direct_to_template, {'template': 'stats.html'} ),
    url(r'^mcdtrac/messages/?$', login_required(view_submissions), name='mcds'),
    url(r'^mcdtrac/xforms/$', login_required(mcdtrac_xforms), name='mcd-xforms'),
    url(r'^mcdtrac/(?P<form_id>\d+)/submissions/$', login_required(view_submissions), name='mcd-submissions'),
    #Export CSV
    url(r"^mcdtrac/submissions.csv$", login_required(submissions_as_csv), name='mcd-all-excel'),
    url(r"^mcdtrac/(?P<pk>\d+)/submissions.csv$", login_required(submissions_as_csv), name='mcd-excel'),
    url(r'^mcdtrac/fhdstats/$', login_required(generic), {
        'model':XFormSubmission,
        'queryset':FHDMaterializedReport,
        'selectable':False,
        'paginated':False,
        'results_title':None,
        'top_columns':[
            ('', 1, None),
            ('Entries', 1, None),
            ('DPT', '2', None),
            ('VACM', '2', None),
            ('VITA', '4', None),
            ('PCV', '6', None),
            ('DORM', '4', None),
            ('RYG', '6', None),
            ('TETN', '5', None),
            ('NPET', '5', None),
            ('BREG', '2', None),
            ('ANCP', '4', None),
            ('HEID', '4', None),
            ('BPBS', '4', None),
        ],
        'columns':[
            #('', False, '', None),
            ('', False, 'entries', None),
            ('M', False, 'dpt_male', None),
            ('F', False, 'dpt_female', None),
            ('M', False, 'vacm_male', None),
            ('F', False, 'vacm_female', None),
            ('M\n(6-11 m)', False, 'vita_male1', None),
            ('F\n(6-11 m)', False, 'vita_female1', None),
            ('M\n(12-59 m)', False, 'vita_male2', None),
            ('F\n(12-59 m)', False, 'vita_female2', None),
            ('PCV1\n(M)', False, 'pcv_pcv1_m', None),
            ('PCV1\n(F)', False, 'pcv_pcv1_f', None),
            ('PCV2\n(M)', False, 'pcv_pcv2_m', None),
            ('PCV2\n(F)', False, 'pcv_pcv2_f', None),
            ('PCV3\n(M)', False, 'pcv_pcv3_m', None),
            ('PCV3\n(F)', False, 'pcv_pcv3_f', None),
            ('M\n(1-4y)', False, 'dorm_male_1to4', None),
            ('F\n(1-4y)', False, 'dorm_female_1to4', None),
            ('M\n(5-14y)', False, 'dorm_male_5to14', None),
            ('F\n(5-14y)', False, 'dorm_female_5to14', None),
            ('Red\n(M)', False, 'ryg_red_male', None),
            ('Red\n(F)', False, 'ryg_red_female', None),
            ('Yellow\n(M)', False, 'ryg_yellow_male', None),
            ('Yellow\n(F)', False, 'ryg_yellow_female', None),
            ('Green\n(M)', False, 'ryg_green_male', None),
            ('Green\n(F)', False, 'ryg_green_female', None),
            ('D1', False, 'tetn_dose1', None),
            ('D2', False, 'tetn_dose2', None),
            ('D3', False, 'tetn_dose3', None),
            ('D4', False, 'tetn_dose4', None),
            ('D5', False, 'tetn_dose5', None),
            ('D1', False, 'npet_dose1', None),
            ('D2', False, 'npet_dose2', None),
            ('D3', False, 'npet_dose3', None),
            ('D4', False, 'npet_dose4', None),
            ('D5', False, 'npet_dose5', None),
            ('M', False, 'breg_male', None),
            ('F', False, 'breg_female', None),
            ('ANC1', False, 'ancp_anc1', None),
            ('ANC4', False, 'ancp_anc4', None),
            ('IPT1', False, 'ancp_ipt1', None),
            ('IPT2', False, 'ancp_ipt2', None),
            ('M', False, 'heid_male', None),
            ('F', False, 'heid_female', None),
            ('Total', False, 'heid_tot', None),
            ('Women', False, 'heid_women', None),
            ('BP (M)', False, 'bpbs_bpm', None),
            ('BP (F)', False, 'bpbs_bpf', None),
            ('BS (M)', False, 'bpbs_bsm', None),
            ('BS (F)', False, 'bpbs_bsf', None),
        ],
        'partial_row':'mcdtrac/partials/fhd_stats_row.html',
        'partial_header':'mcdtrac/partials/fhd_stats_header.html',
        'partial_base': 'mcdtrac/partials/fhd_stats_partial_base.html',
        'base_template':'mcdtrac/fhd_timeslider_base.html',
        'needs_date':True,
        'dates': fhd_get_xform_dates,
        'embbed_time_slider': True,
        'has_chart': False,
    }, name='fhd-stats'),

)
